<?php

$uri = get_template_directory_uri() . '/liquid/assets/img/demos/';

// Demos

$demos = array(
	'original' => array(
		'title'       => esc_html__( 'Original Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'originalhub.jpg',
		'preview'     => 'https://originalhub.liquid-themes.com/',
		'has_widgets' => true,
	),
	'darkapp' => array(
		'title'       => esc_html__( 'Dark App', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'darkapp.jpg',
		'preview'     => 'https://darkapppro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'barber' => array(
		'title'       => esc_html__( 'Barber', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'barber.jpg',
		'preview'     => 'https://barberpro.liquid-themes.com/',
		'has_widgets' => true,
	),
	'music' => array(
		'title'       => esc_html__( 'Music', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'music.jpg',
		'preview'     => 'https://musicpro.liquid-themes.com/',
		'has_widgets' => true,
	),
	'marketing' => array(
		'title'       => esc_html__( 'Marketing', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'marketing.jpg',
		'preview'     => 'https://marketingpro.liquid-themes.com/',
		'has_widgets' => true,
	),
	'verticalportfolio' => array(
		'title'       => esc_html__( 'Vertical Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'verticalporfolio.jpg',
		'preview'     => 'https://verticalportfoliopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'company' => array(
		'title'       => esc_html__( 'Company', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'company.jpg',
		'preview'     => 'https://company.liquid-themes.com/',
		'has_widgets' => true,
	),
    'lookbook' => array(
		'title'       => esc_html__( 'Lookbook', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'lookbook.jpg',
		'preview'     => 'https://lookbookpro.liquid-themes.com',
		'has_widgets' => true,
	),
    'appblocks' => array(
		'title'       => esc_html__( 'App Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'appblocks.jpg',
		'preview'     => 'https://appblockspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'gridportfolio' => array(
		'title'       => esc_html__( 'Grid Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'gridportfolio.jpg',
		'preview'     => 'https://gridportfoliopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'stickyblog' => array(
		'title'       => esc_html__( 'Sticky Blog', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'stickyblog.jpg',
		'preview'     => 'https://stickyblogpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'newsletter' => array(
		'title'       => esc_html__( 'Newsletter Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'newsletterhub.jpg',
		'preview'     => 'https://newsletterpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'split' => array(
		'title'       => esc_html__( 'Split', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'split.jpg',
		'preview'     => 'https://splitpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'modernblocks' => array(
		'title'       => esc_html__( 'Modern Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernblocks.jpg',
		'preview'     => 'https://modernblockspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetriccorporate' => array(
		'title'       => esc_html__( 'Asymmetric Corporate', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetriccorporate.jpg',
		'preview'     => 'https://asymmetric-corporatepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'creativeatelier' => array(
		'title'       => esc_html__( 'Creative Atelier', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'creativeatelier.jpg',
		'preview'     => 'https://creativeatelierpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'classic' => array(
		'title'       => esc_html__( 'Classic', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'classic.jpg',
		'preview'     => 'https://classicpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'photography' => array(
		'title'       => esc_html__( 'Photography', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'photography.jpg',
		'preview'     => 'https://photographypro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'productshop' => array(
		'title'       => esc_html__( 'Product Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'productshop.jpg',
		'preview'     => 'https://productshoppro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'darkportfolio' => array(
		'title'       => esc_html__( 'Dark Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'darkportfolio.jpg',
		'preview'     => 'https://darkportfoliopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'adaptivecolors' => array(
		'title'       => esc_html__( 'Adaptive Colors', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'adaptivecolors.jpg',
		'preview'     => 'https://adaptivecolorspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'corporate' => array(
		'title'       => esc_html__( 'Corporate', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'corporate.jpg',
		'preview'     => 'https://corporatepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'modernbusiness' => array(
		'title'       => esc_html__( 'Modern Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernbusiness.jpg',
		'preview'     => 'https://modernbusinesspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'projectslider' => array(
		'title'       => esc_html__( 'Project Slider', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'projectslider.jpg',
		'preview'     => 'https://projectsliderpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'modernshop' => array(
		'title'       => esc_html__( 'Modern Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernshop.jpg',
		'preview'     => 'https://modernashop.liquid-themes.com/',
		'has_widgets' => true,
	),
    'softwarehub' => array(
		'title'       => esc_html__( 'Software Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'softwarehub.jpg',
		'preview'     => 'https://softwarepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'modernagency' => array(
		'title'       => esc_html__( 'Modern Agency', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernagency.jpg',
		'preview'     => 'https://modernagencypro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'classicsaas' => array(
		'title'       => esc_html__( 'Classic SaaS', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'classicsaas.jpg',
		'preview'     => 'https://classicsaaspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetricportfolio' => array(
		'title'       => esc_html__( 'Asymmetric Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricportfolio.jpg',
		'preview'     => 'https://asymmetric-portfoliopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'digitalstudio' => array(
		'title'       => esc_html__( 'Digital Studio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'digitalstudio.jpg',
		'preview'     => 'https://digitalstudiopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'portfoliohub' => array(
		'title'       => esc_html__( 'Portfolio Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfoliohub.jpg',
		'preview'     => 'https://pfhubpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'imagetrail' => array(
		'title'       => esc_html__( 'Image Trail', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'imagetrail.jpg',
		'preview'     => 'https://imagetrailpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'portfolioboxes' => array(
		'title'       => esc_html__( 'Portfolio Boxes', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolioboxes.jpg',
		'preview'     => 'https://portfolioboxespro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'grocery' => array(
		'title'       => esc_html__( 'Grocery', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'grocery.jpg',
		'preview'     => 'https://grocerypro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetriclanding' => array(
		'title'       => esc_html__( 'Asymmetric Landing', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetriclanding.jpg',
		'preview'     => 'https://asymmetric-landingpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'architecture' => array(
		'title'       => esc_html__( 'Architecture Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture.jpg',
		'preview'     => 'https://architecturepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetricbusiness' => array(
		'title'       => esc_html__( 'Asymmetric Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricbusiness.jpg',
		'preview'     => 'https://asymmetric-businesspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'seohub' => array(
		'title'       => esc_html__( 'SEO Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'seohub.jpg',
		'preview'     => 'https://seopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'businessstartup' => array(
		'title'       => esc_html__( 'Business Startup', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'businessstartup.jpg',
		'preview'     => 'https://businessstartuppro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'marketplace' => array(
		'title'       => esc_html__( 'Marketplace', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'marketplace.jpg',
		'preview'     => 'https://marketplacepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'digitalhub' => array(
		'title'       => esc_html__( 'Digital Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'digitalhub.jpg',
		'preview'     => 'https://digitalpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'businessblocks' => array(
		'title'       => esc_html__( 'Business Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'businessblocks.jpg',
		'preview'     => 'https://businessblockspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'startup' => array(
		'title'       => esc_html__( 'Startup Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'startup.jpg',
		'preview'     => 'https://startup.liquid-themes.com/',
		'has_widgets' => true,
	),
    'designer' => array(
		'title'       => esc_html__( 'Designer', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'designer.jpg',
		'preview'     => 'https://designerpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'creativeservices' => array(
		'title'       => esc_html__( 'Creative Services', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'creativeservices.jpg',
		'preview'     => 'https://creativeservicespro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'modernmobile' => array(
		'title'       => esc_html__( 'Modern Mobile', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernmobile.jpg',
		'preview'     => 'https://mobilemodernpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'mobileapp' => array(
		'title'       => esc_html__( 'Mobile App', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'mobileapp.jpg',
		'preview'     => 'https://mobilepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'retailshop' => array(
		'title'       => esc_html__( 'Retail Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'retailshop.jpg',
		'preview'     => 'https://retailpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'portfoliopanel' => array(
		'title'       => esc_html__( 'Portfolio Panel', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfoliopanel.jpg',
		'preview'     => 'https://portfoliopanelpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'parallax' => array(
		'title'       => esc_html__( 'Parallax', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'parallax.jpg',
		'preview'     => 'https://parallaxpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'sidefolio' => array(
		'title'       => esc_html__( 'SideFolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'sidefolio.jpg',
		'preview'     => 'https://sidefoliopro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'saashub' => array(
		'title'       => esc_html__( 'SaasHub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'saashub.jpg',
		'preview'     => 'https://saaspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetricfreelancer' => array(
		'title'       => esc_html__( 'Asymmetric Freelancer', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricfreelancer.jpg',
		'preview'     => 'https://asymmetric-freelancerpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'itbusiness' => array(
		'title'       => esc_html__( 'IT Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'itbusiness.jpg',
		'preview'     => 'https://itbusinesspro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'fashionstore' => array(
		'title'       => esc_html__( 'Fashion Store', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'fashionstore.jpg',
		'preview'     => 'https://fashionstorepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'asymmetricagency' => array(
		'title'       => esc_html__( 'Asymmetric Agency', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricagency.jpg',
		'preview'     => 'https://asymmetric-agencypro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'shadow' => array(
		'title'       => esc_html__( 'Shadow', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'shadow.jpg',
		'preview'     => 'https://shadowpro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'multiuse' => array(
		'title'       => esc_html__( 'Multi Use', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'multiuse.jpg',
		'preview'     => 'https://multiusepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'customerstories' => array(
		'title'       => esc_html__( 'Customer Stories', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'customerstories.jpg',
		'preview'     => 'https://customerstoriespro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'insurance' => array(
		'title'       => esc_html__( 'Insurance', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'insurance.jpg',
		'preview'     => 'https://insurancepro.liquid-themes.com/',
		'has_widgets' => true,
	),
    'flexible' => array(
		'title'       => esc_html__( 'Flexible', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'flexible.jpg',
		'preview'     => 'https://flexible.liquid-themes.com/',
		'has_widgets' => true,
	),
	'ecommerceagency' => array(
		'title'       => esc_html__( 'Ecommerce Agency', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'ecommerceagency.jpg',
		'preview'     => 'https://ecommerceagency.liquid-themes.com/',
		'has_widgets' => true,
	),
	'multipurpose' => array(
		'title'       => esc_html__( 'Multi Purpose', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'multipurpose.jpg',
		'preview'     => 'https://multipurpose.liquid-themes.com/',
		'has_widgets' => true,
	),
	'kids' => array(
		'title'       => esc_html__( 'Kids', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'kids.jpg',
		'preview'     => 'https://kids.liquid-themes.com/',
		'has_widgets' => true,
	),
	'lawyer' => array(
		'title'       => esc_html__( 'Lawyer', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'lawyer.jpg',
		'preview'     => 'https://lawyer.liquid-themes.com/',
		'has_widgets' => true,
	),
	'service' => array(
		'title'       => esc_html__( 'Service', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'servicepro.jpg',
		'preview'     => 'https://servicepro.liquid-themes.com/',
		'has_widgets' => true,
	),
	// Elementor Demos
	'original_el' => array(
		'title'       => esc_html__( 'Original Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'originalhub.jpg',
		'preview'     => 'https://originalhub.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'asymmetricagency_el' => array(
		'title'       => esc_html__( 'Asymmetric Agency', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricagency.jpg',
		'preview'     => 'https://asymmetric-agencypro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'company_el' => array(
		'title'       => esc_html__( 'Company', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'company.jpg',
		'preview'     => 'https://company.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'appblocks_el' => array(
		'title'       => esc_html__( 'App Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'appblocks.jpg',
		'preview'     => 'https://appblockspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'darkapp_el' => array(
		'title'       => esc_html__( 'Dark App', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'darkapp.jpg',
		'preview'     => 'https://darkapppro.liquid-themes.com/',
		'has_widgets' => false,
		'builder'     => 'elementor',
	),
	'digitalhub_el' => array(
		'title'       => esc_html__( 'Digital Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'digitalhub.jpg',
		'preview'     => 'https://digitalpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'digitalstudio_el' => array(
		'title'       => esc_html__( 'Digital Studio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'digitalstudio.jpg',
		'preview'     => 'https://digitalstudiopro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'ecommerceagency_el' => array(
		'title'       => esc_html__( 'Ecommerce Agency', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'ecommerceagency.jpg',
		'preview'     => 'https://ecommerceagency.liquid-themes.com/',
		'has_widgets' => false,
		'builder'     => 'elementor',
	),
	'fashionstore_el' => array(
		'title'       => esc_html__( 'Fashion Store', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'fashionstore.jpg',
		'preview'     => 'https://fashionstorepro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'projectslider_el' => array(
		'title'       => esc_html__( 'Project Slider', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'projectslider.jpg',
		'preview'     => 'https://projectsliderpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'saashub_el' => array(
		'title'       => esc_html__( 'SaasHub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'saashub.jpg',
		'preview'     => 'https://saaspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'lawyer_el' => array(
		'title'       => esc_html__( 'Lawyer', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'lawyer.jpg',
		'preview'     => 'https://lawyer.liquid-themes.com/',
		'has_widgets' => false,
		'builder'     => 'elementor',
	),
	'modernagency_el' => array(
		'title'       => esc_html__( 'Modern Agency', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernagency.jpg',
		'preview'     => 'https://modernagencypro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'modernbusiness_el' => array(
		'title'       => esc_html__( 'Modern Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernbusiness.jpg',
		'preview'     => 'https://modernbusinesspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'businessstartup_el' => array(
		'title'       => esc_html__( 'Business Startup', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'businessstartup.jpg',
		'preview'     => 'https://businessstartuppro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'seohub_el' => array(
		'title'       => esc_html__( 'SEO Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'seohub.jpg',
		'preview'     => 'https://seopro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'productshop_el' => array(
		'title'       => esc_html__( 'Product Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'productshop.jpg',
		'preview'     => 'https://productshoppro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'asymmetricbusiness_el' => array(
		'title'       => esc_html__( 'Asymmetric Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricbusiness.jpg',
		'preview'     => 'https://asymmetric-businesspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'marketing_el' => array(
		'title'       => esc_html__( 'Marketing', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'marketing.jpg',
		'preview'     => 'https://marketingpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'adaptivecolors_el' => array(
		'title'       => esc_html__( 'Adaptive Colors', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'adaptivecolors.jpg',
		'preview'     => 'https://adaptivecolorspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'classic_el' => array(
		'title'       => esc_html__( 'Classic', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'classic.jpg',
		'preview'     => 'https://classicpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'flexible_el' => array(
		'title'       => esc_html__( 'Flexible', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'flexible.jpg',
		'preview'     => 'https://flexible.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'creativeatelier_el' => array(
		'title'       => esc_html__( 'Creative Atelier', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'creativeatelier.jpg',
		'preview'     => 'https://creativeatelierpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'customerstories_el' => array(
		'title'       => esc_html__( 'Customer Stories', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'customerstories.jpg',
		'preview'     => 'https://customerstoriespro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor',
	),
	'creativeservices_el' => array(
		'title'       => esc_html__( 'Creative Services', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'creativeservices.jpg',
		'preview'     => 'https://creativeservicespro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'music_el' => array(
		'title'       => esc_html__( 'Music', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'music.jpg',
		'preview'     => 'https://musicpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'itbusiness_el' => array(
		'title'       => esc_html__( 'IT Business', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'itbusiness.jpg',
		'preview'     => 'https://itbusinesspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'softwarehub_el' => array(
		'title'       => esc_html__( 'Software Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'softwarehub.jpg',
		'preview'     => 'https://softwarepro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'modernshop_el' => array(
		'title'       => esc_html__( 'Modern Shop', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'modernshop.jpg',
		'preview'     => 'https://modernashop.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'handmade_el' => array(
		'title'       => esc_html__( 'Handmade', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'handmade.jpg',
		'preview'     => 'https://handmade.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'blog_el' => array(
		'title'       => esc_html__( 'Classic Magazine', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'magazine.jpg',
		'preview'     => 'https://blog.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'restaurant_el' => array(
		'title'       => esc_html__( 'Restaurant', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'restaurant.jpg',
		'preview'     => 'https://restauranthub.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'spa_el' => array(
		'title'       => esc_html__( 'SPA', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'spa.jpg',
		'preview'     => 'https://spa.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'corporate_el' => array(
		'title'       => esc_html__( 'Corporate', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'corporate.jpg',
		'preview'     => 'https://corporatepro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'kids_el' => array(
		'title'       => esc_html__( 'Kids', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'kids.jpg',
		'preview'     => 'https://kids.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'barber_el' => array(
		'title'       => esc_html__( 'Barber', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'barber.jpg',
		'preview'     => 'https://barberpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'architecture_el' => array(
		'title'       => esc_html__( 'Architecture Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture.jpg',
		'preview'     => 'https://architecturepro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'modernblocks_el' => array(
		'title'       => esc_html__( 'Modern Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'modernblocks.jpg',
		'preview'     => 'https://modernblockspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'photography_el' => array(
		'title'       => esc_html__( 'Photography', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'photography.jpg',
		'preview'     => 'https://photographypro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'asymmetriclanding_el' => array(
		'title'       => esc_html__( 'Asymmetric Landing', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetriclanding.jpg',
		'preview'     => 'https://asymmetric-landingpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'businessblocks_el' => array(
		'title'       => esc_html__( 'Business Blocks', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'businessblocks.jpg',
		'preview'     => 'https://businessblockspro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'startup_el' => array(
		'title'       => esc_html__( 'Startup Hub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'startup.jpg',
		'preview'     => 'https://startup.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'multipurpose_el' => array(
		'title'       => esc_html__( 'Multi Purpose', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'multipurpose.jpg',
		'preview'     => 'https://multipurpose.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'insurance_el' => array(
		'title'       => esc_html__( 'Insurance', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'insurance.jpg',
		'preview'     => 'https://insurancepro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'blog2_el' => array(
		'title'       => esc_html__( 'Minimal Blog', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'blog2.jpg',
		'preview'     => 'https://blog2.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'events_el' => array(
		'title'       => esc_html__( 'Events', 'hub' ),
		'description' => '',
		'screenshot'  => $uri . 'event.jpg',
		'preview'     => 'https://events.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'gridportfolio_el' => array(
		'title'       => esc_html__( 'Grid Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'gridportfolio.jpg',
		'preview'     => 'https://gridportfoliopro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'masonryshop_el' => array(
		'title'       => esc_html__( 'Masonry Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'masonryshop.jpg',
		'preview'     => 'https://masonryshop.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub1_el' => array(
		'title'       => esc_html__( 'StartHub', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub1.jpg',
		'preview'     => 'https://starthubone.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub2_el' => array(
		'title'       => esc_html__( 'StartHub Two', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub2.jpg',
		'preview'     => 'https://starthubtwo.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub3_el' => array(
		'title'       => esc_html__( 'StartHub Three', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub3.jpg',
		'preview'     => 'https://starthubthree.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub4_el' => array(
		'title'       => esc_html__( 'StartHub Four', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub4.jpeg',
		'preview'     => 'https://starthub-4.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub5_el' => array(
		'title'       => esc_html__( 'StartHub Five', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub5.jpeg',
		'preview'     => 'https://starthub-5.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub6_el' => array(
		'title'       => esc_html__( 'StartHub Six', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub6.jpeg',
		'preview'     => 'https://starthub-6.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub7_el' => array(
		'title'       => esc_html__( 'StartHub Seven', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub7.jpeg',
		'preview'     => 'https://starthub-7.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthub8_el' => array(
		'title'       => esc_html__( 'StartHub Eight', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthub8.jpg',
		'preview'     => 'https://starthub-8.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'starthubx_el' => array(
		'title'       => esc_html__( 'StartHub X', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'starthubx.jpg',
		'preview'     => 'https://starthub-x.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'asymmetric8_el' => array(
		'title'       => esc_html__( 'Asymmetric Eight', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetric8.jpg',
		'preview'     => 'https://asymmetriceightpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'asymmetric9_el' => array(
		'title'       => esc_html__( 'Asymmetric Nine', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetric9.jpg',
		'preview'     => 'https://asymmetric-9.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'asymmetricportfolio_el' => array(
		'title'       => esc_html__( 'Asymmetric Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'asymmetricportfolio.jpg',
		'preview'     => 'https://asymmetric-portfoliopro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'darkportfolio_el' => array(
		'title'       => esc_html__( 'Dark Portfolio', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'darkportfolio.jpg',
		'preview'     => 'https://darkportfoliopro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'shadow_el' => array(
		'title'       => esc_html__( 'Shadow', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'shadow.jpg',
		'preview'     => 'https://shadowpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'yoga_el' => array(
		'title'       => esc_html__( 'Yoga', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'yoga.jpeg',
		'preview'     => 'https://yogapro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'magazine_viral_el' => array(
		'title'       => esc_html__( 'Magazine Viral', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'magazine-viral.jpeg',
		'preview'     => 'https://magazineviralpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'fashion_blog_el' => array(
		'title'       => esc_html__( 'Fashion Blog', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'fashion-blog.jpeg',
		'preview'     => 'https://fashionblogpro.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'seolanding_el' => array(
		'title'       => esc_html__( 'SEO Landing', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'seolanding.jpeg',
		'preview'     => 'https://seolanding.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'sneakersshop_el' => array(
		'title'       => esc_html__( 'Sneakers Shop', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'sneakers-shop.jpg',
		'preview'     => 'https://sneakers.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'darkai_el' => array(
		'title'       => esc_html__( 'Dark AI', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'darkai.jpg',
		'preview'     => 'https://dark-ai.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'beauty_el' => array(
		'title'       => esc_html__( 'Beauty', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'beauty.jpg',
		'preview'     => 'https://beauty.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
	'hotel_el' => array(
		'title'       => esc_html__( 'Hotel', 'hub' ),	
		'description' => '',
		'screenshot'  => $uri . 'hotel.jpg',
		'preview'     => 'https://hotel.liquid-themes.com/',
		'has_widgets' => true,
		'builder'     => 'elementor'
	),
);